from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st


# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
# Forecast JSON generated by:
#   python scripts/forecast_next_24h.py --run runs/exp_transformer_physics_v0
#
# This file is expected to contain:
#   - model/run metadata
#   - peak summary
#   - 24 forecast rows with mean, sigma, intervals, and risk labels
# -----------------------------------------------------------------------------
FORECAST_JSON_PATH = Path("reports/latest_forecast/next_24h_forecast.json")


# -----------------------------------------------------------------------------
# Data loading
# -----------------------------------------------------------------------------
@st.cache_data
def load_forecast(path: Path) -> dict:
    """
    Load forecast JSON from disk.

    Returns:
        Parsed JSON as a Python dictionary.

    Raises:
        FileNotFoundError: if the forecast file does not exist.
    """
    if not path.exists():
        raise FileNotFoundError(f"Forecast file not found: {path}")
    return json.loads(path.read_text())


def build_forecast_df(payload: dict) -> pd.DataFrame:
    """
    Convert the forecast list into a pandas DataFrame.

    Expected columns in each forecast row:
        - timestamp
        - mean_mw
        - sigma_mw
        - lower_80_mw
        - upper_80_mw
        - lower_95_mw
        - upper_95_mw
        - risk_level
        - is_peak_mean
        - is_peak_upper95

    Returns:
        DataFrame with timestamp parsed to datetime.
    """
    df = pd.DataFrame(payload["forecast"])
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    return df


# -----------------------------------------------------------------------------
# UI helper functions
# -----------------------------------------------------------------------------
def style_risk(value: str) -> str:
    """
    Convert raw risk labels into decorated dashboard labels.
    """
    value = str(value).lower()
    if value == "high":
        return "🔴 HIGH"
    if value == "moderate":
        return "🟠 MODERATE"
    return "🟢 NORMAL"


def render_risk_banner(peak_risk: str) -> None:
    """
    Show top-level alert banner based on peak risk level.
    """
    risk_label = str(peak_risk).lower()

    if risk_label == "high":
        st.error("⚠️ High peak-load risk detected in the next 24 hours.")
    elif risk_label == "moderate":
        st.warning("⚠️ Moderate peak-load risk detected in the next 24 hours.")
    else:
        st.success("Peak-load risk is within normal range.")


# -----------------------------------------------------------------------------
# Chart construction
# -----------------------------------------------------------------------------
def make_forecast_chart(df: pd.DataFrame) -> go.Figure:
    """
    Build the main probabilistic forecast chart.

    Layers:
        1. 95% interval band
        2. 80% interval band
        3. Mean forecast line
        4. Peak marker
        5. High-risk hour markers
        6. Moderate-risk hour markers
    """
    fig = go.Figure()

    # -------------------------------------------------------------------------
    # 95% prediction interval
    # -------------------------------------------------------------------------
    fig.add_trace(
        go.Scatter(
            x=df["timestamp"],
            y=df["upper_95_mw"],
            mode="lines",
            line=dict(width=0),
            hoverinfo="skip",
            showlegend=False,
            name="Upper 95%",
        )
    )

    fig.add_trace(
        go.Scatter(
            x=df["timestamp"],
            y=df["lower_95_mw"],
            mode="lines",
            line=dict(width=0),
            fill="tonexty",
            name="95% Interval",
            hovertemplate="95% Interval<br>%{x}<br>%{y:.0f} MW<extra></extra>",
        )
    )

    # -------------------------------------------------------------------------
    # 80% prediction interval
    # -------------------------------------------------------------------------
    fig.add_trace(
        go.Scatter(
            x=df["timestamp"],
            y=df["upper_80_mw"],
            mode="lines",
            line=dict(width=0),
            hoverinfo="skip",
            showlegend=False,
            name="Upper 80%",
        )
    )

    fig.add_trace(
        go.Scatter(
            x=df["timestamp"],
            y=df["lower_80_mw"],
            mode="lines",
            line=dict(width=0),
            fill="tonexty",
            name="80% Interval",
            hovertemplate="80% Interval<br>%{x}<br>%{y:.0f} MW<extra></extra>",
        )
    )

    # -------------------------------------------------------------------------
    # Mean forecast line
    # -------------------------------------------------------------------------
    fig.add_trace(
        go.Scatter(
            x=df["timestamp"],
            y=df["mean_mw"],
            mode="lines+markers",
            name="Mean Forecast",
            hovertemplate="%{x}<br>Mean: %{y:.0f} MW<extra></extra>",
        )
    )

    # -------------------------------------------------------------------------
    # Peak marker
    # Highlight the hour with the maximum mean forecast.
    # -------------------------------------------------------------------------
    peak_idx = df["mean_mw"].idxmax()

    fig.add_trace(
        go.Scatter(
            x=[df.loc[peak_idx, "timestamp"]],
            y=[df.loc[peak_idx, "mean_mw"]],
            mode="markers+text",
            name="Peak Forecast",
            marker=dict(
                size=12,
                color="red",
                symbol="diamond",
            ),
            text=["Peak"],
            textposition="top center",
            hovertemplate="Peak Forecast<br>%{x}<br>%{y:.0f} MW<extra></extra>",
        )
    )

    # -------------------------------------------------------------------------
    # High-risk hour markers
    # -------------------------------------------------------------------------
    if "risk_level" in df.columns:
        high_df = df[df["risk_level"].str.lower() == "high"]

        if not high_df.empty:
            fig.add_trace(
                go.Scatter(
                    x=high_df["timestamp"],
                    y=high_df["mean_mw"],
                    mode="markers",
                    name="High-Risk Hour",
                    marker=dict(
                        size=10,
                        color="red",
                        symbol="x",
                    ),
                    hovertemplate="High-Risk Hour<br>%{x}<br>Mean: %{y:.0f} MW<extra></extra>",
                )
            )

    # -------------------------------------------------------------------------
    # Moderate-risk hour markers
    # -------------------------------------------------------------------------
    if "risk_level" in df.columns:
        moderate_df = df[df["risk_level"].str.lower() == "moderate"]

        if not moderate_df.empty:
            fig.add_trace(
                go.Scatter(
                    x=moderate_df["timestamp"],
                    y=moderate_df["mean_mw"],
                    mode="markers",
                    name="Moderate-Risk Hour",
                    marker=dict(
                        size=8,
                        color="orange",
                        symbol="circle-open",
                    ),
                    hovertemplate="Moderate-Risk Hour<br>%{x}<br>Mean: %{y:.0f} MW<extra></extra>",
                )
            )

    fig.update_layout(
        title="Next 24-Hour Load Forecast",
        xaxis_title="Timestamp",
        yaxis_title="Load (MW)",
        hovermode="x unified",
        template="plotly_white",
        margin=dict(l=20, r=20, t=50, b=20),
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1,
        ),
    )

    return fig


# -----------------------------------------------------------------------------
# Main dashboard
# -----------------------------------------------------------------------------
def main() -> None:
    """
    Streamlit app entrypoint.

    Flow:
        1. Load latest forecast JSON
        2. Extract metadata and forecast rows
        3. Show KPI cards
        4. Show peak-risk banner
        5. Render probabilistic chart
        6. Show metadata / peak summary panel
        7. Show downloadable forecast table
    """
    st.set_page_config(
        page_title="Probabilistic Load Forecast Dashboard",
        layout="wide",
    )

    st.title("⚡ Physics-Constrained Probabilistic Load Forecast")
    st.caption("24-hour ahead system load forecast with uncertainty bands and peak-risk alerting")

    # -------------------------------------------------------------------------
    # Load forecast file
    # -------------------------------------------------------------------------
    try:
        payload = load_forecast(FORECAST_JSON_PATH)
    except FileNotFoundError as e:
        st.error(str(e))
        st.info(
            "Run the inference script first:\n\n"
            "`python scripts/forecast_next_24h.py --run runs/exp_transformer_physics_v0`"
        )
        return

    df = build_forecast_df(payload)

    # -------------------------------------------------------------------------
    # Peak summary
    # Use values from JSON if present; otherwise safely fall back to computed ones.
    # -------------------------------------------------------------------------
    peak = payload.get("peak_summary", {})
    peak_mean = peak.get("peak_mean_mw", float(df["mean_mw"].max()))
    peak_ts = peak.get("peak_timestamp", str(df.loc[df["mean_mw"].idxmax(), "timestamp"]))
    peak_risk = peak.get("peak_risk_level", "normal")
    peak_threshold = peak.get("peak_threshold_mw", 0.0)
    peak_upper95 = peak.get("peak_upper_95_mw", 0.0)

    # -------------------------------------------------------------------------
    # KPI cards
    # -------------------------------------------------------------------------
    avg_load = float(df["mean_mw"].mean())
    max_sigma = float(df["sigma_mw"].max())

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Peak Forecast Load", f"{peak_mean:,.0f} MW")
    c2.metric("Peak Hour", str(peak_ts))
    c3.metric("Average Forecast Load", f"{avg_load:,.0f} MW")
    c4.metric("Max Uncertainty (σ)", f"{max_sigma:,.0f} MW")

    # -------------------------------------------------------------------------
    # Top-level risk alert
    # -------------------------------------------------------------------------
    render_risk_banner(peak_risk)

    st.markdown("---")

    # -------------------------------------------------------------------------
    # Main layout:
    # left  -> chart
    # right -> model metadata + peak summary
    # -------------------------------------------------------------------------
    left, right = st.columns([2, 1])

    with left:
        st.subheader("Probabilistic Forecast")
        fig = make_forecast_chart(df)
        st.plotly_chart(fig, use_container_width=True)

    with right:
        st.subheader("Model Metadata")
        st.write(f"**Run Name:** {payload.get('run_name', 'N/A')}")
        st.write(f"**Source:** {payload.get('source', 'N/A')}")
        st.write(f"**Target Column:** {payload.get('target_col', 'N/A')}")
        st.write(f"**Context Length:** {payload.get('context_length', 'N/A')} hours")
        st.write(f"**Forecast Horizon:** {payload.get('horizon', 'N/A')} hours")
        st.write(f"**Last Context Timestamp:** {payload.get('last_context_timestamp', 'N/A')}")

        st.subheader("Peak Summary")
        st.write(f"**Peak Threshold:** {peak_threshold:,.0f} MW")
        st.write(f"**Peak Mean Forecast:** {peak_mean:,.0f} MW")
        st.write(f"**Peak Upper 95%:** {peak_upper95:,.0f} MW")
        st.write(f"**Peak Risk Level:** {style_risk(peak_risk)}")

        with st.expander("Feature Columns"):
            st.write(payload.get("feature_cols", []))

    st.markdown("---")

    # -------------------------------------------------------------------------
    # Forecast table
    # -------------------------------------------------------------------------
    st.subheader("Forecast Table")

    display_df = df.copy()
    display_df["timestamp"] = display_df["timestamp"].dt.strftime("%Y-%m-%d %H:%M")

    if "risk_level" in display_df.columns:
        display_df["risk_level"] = display_df["risk_level"].map(style_risk)

    display_df = display_df.rename(
        columns={
            "timestamp": "Timestamp",
            "mean_mw": "Mean (MW)",
            "sigma_mw": "Sigma (MW)",
            "lower_80_mw": "Lower 80% (MW)",
            "upper_80_mw": "Upper 80% (MW)",
            "lower_95_mw": "Lower 95% (MW)",
            "upper_95_mw": "Upper 95% (MW)",
            "risk_level": "Risk Level",
            "is_peak_mean": "Peak Mean Flag",
            "is_peak_upper95": "Peak Upper95 Flag",
        }
    )

    st.dataframe(display_df, width="stretch", hide_index=True)

    # -------------------------------------------------------------------------
    # CSV download
    # -------------------------------------------------------------------------
    csv_bytes = display_df.to_csv(index=False).encode("utf-8")
    st.download_button(
        label="Download Forecast CSV",
        data=csv_bytes,
        file_name="next_24h_forecast.csv",
        mime="text/csv",
    )


if __name__ == "__main__":
    main()